name: Python Tests

on:
  push:
    branches:
      - main # Trigger on push to main branch
  pull_request:
    branches:
      - main # Trigger on PR to main branch

jobs:
  test:
    runs-on: ubuntu-latest # Use an Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checkout the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Use Python 3.9 (or the version you prefer)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
